### ISSUE TITLE
Ejemplo de despliegue con docker?

### ISSUE THREAD

**Issue by erral** [albfernandez/oaw#1]
Hola:

Buscando en Google he llegado a este repositorio...

Hemos comenzado a instalar el Rastreador OAW (https://administracionelectronica.gob.es/ctt/oaw), y al intentar compilarlo a WAR hemos visto que tiene un perfil docker, por lo que nos preguntamos si tienes algún ejemplo de despliegue de la herramienta con docker.

Gracias :)

**Comment by erral** [comment]
Acabo de ver que dentro de la carpeta OAW del ZIP que se descarga desde la web del CTT hay un ejemplo de docker-compose.yml :)

**Comment by albfernandez** [comment]
Lo siento, no he probado en docker, aquí simplemente tengo una copia de los fuentes

**Comment by erral** [comment]
GRacias,
